title: Kyungmin Kwon
email: kyongmini@snu.ac.kr
description: >- # this means to ignore newlines until "baseurl:"
  Research website of Kyungmin Kwon.
baseurl: "" 
url: "http://kyongmini.github.io" 

include:
  - files
  - files/MDQL
  - files/QOstudy
  - files/NOstudy
# Header Settings
header_background: "#0a192f"

# Social Media
twitter_username: your_twitter_handle 
linkedin_username: your_linkedin_handle 
github_username: your_github_handle 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/